export const copy = (value, fallback) => (value !== undefined && value !== null && String(value).trim() !== '' ? value : fallback)

export const DEFAULT_ABOUT = {
  heroLabel: 'About us',
  title: 'Style with purpose. Made for your everyday.',
  subtitle: '',
  description: 'We create thoughtfully selected pieces that make getting dressed feel simple, confident, and personal.',
  imageUrl: '',
  missionLabel: 'Our mission',
  missionHeading: 'Our mission is simple.',
  mission: 'To make great style feel easy, expressive, and within reach for every customer.',
  missionDescription: 'We focus on thoughtful collections, dependable quality, and a seamless shopping experience from discovery to delivery.',
  offerLabel: 'What we offer',
  offerHeading: 'Pieces that work beautifully across real, everyday moments.',
  offer1Title: 'New arrivals',
  offer1Description: 'Curated with a focus on comfort, confidence, and character.',
  offer2Title: 'Everyday essentials',
  offer2Description: 'Curated with a focus on comfort, confidence, and character.',
  offer3Title: 'Statement styles',
  offer3Description: 'Curated with a focus on comfort, confidence, and character.',
  offer4Title: 'Gifting favourites',
  offer4Description: 'Thoughtful choices for the people you love.',
  qualityHeading: 'Our commitment to quality',
  qualityDescription: 'Every product is selected with a focus on quality, comfort and a reliable customer experience.',
  promise1: 'Carefully selected materials',
  promise2: 'Thoughtful, wearable design',
  promise3: 'Quality-focused finishing',
  promise4: 'Reliable product experience',
  promise5: 'Made for real everyday life',
  promise6: 'Customer satisfaction first',
  valuesLabel: 'Why customers choose us',
  valueOneTitle: 'Thoughtfully made',
  valueOne: 'Considered products and details chosen for everyday life.',
  valueTwoTitle: 'Made to last',
  valueTwo: 'An enduring approach to quality, comfort, and style.',
  valueThreeTitle: 'Customer first',
  valueThree: 'A warm, reliable experience at every step.',
  valueFourTitle: 'Always evolving',
  valueFour: 'Fresh perspective with the essentials you trust.',
  visionLabel: 'Our vision',
  vision: 'To become a trusted destination for style that feels personal, practical, and inspiring.',
  experienceLabel: 'Experience StaffArc',
  experienceText: 'Find the pieces that feel most like you, then make them part of your story.',
  experienceCtaText: 'Shop all products',
  experienceCtaLink: '/plp',
}

export const DEFAULT_CONTACT = {
  heroLabel: 'Get in touch',
  heroTitle: 'We would love to hear from you.',
  heroDescription: 'Questions about a product or an order? Reach us any day of the week.',
  phoneLabel: 'Phone',
  phone: '',
  emailLabel: 'Email',
  email: '',
  addressLabel: 'Address',
  address: '',
  hoursLabel: 'Business hours',
  workingHours: '',
  whatsapp: '',
  socialHeading: 'Follow StaffArc',
  formLabel: 'Send a message',
  formHeading: 'How can we help?',
  formNameLabel: 'Name',
  formNamePlaceholder: 'Your name',
  formPhoneLabel: 'Phone',
  formPhonePlaceholder: 'Your phone number',
  formEmailLabel: 'Email',
  formEmailPlaceholder: 'Your email address',
  formMessageLabel: 'Message',
  formMessagePlaceholder: 'Write your message here',
  formSubmitText: 'Send message',
  formSuccessMessage: 'Thanks! We will get back to you shortly.',
}

export const SOCIAL_LABELS = {
  instagram: 'Instagram',
  facebook: 'Facebook',
  youtube: 'YouTube',
  twitter: 'Twitter / X',
  linkedin: 'LinkedIn',
  whatsapp: 'WhatsApp',
}
